version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - /home/howboring/Projects/qg_devboard:/workspace:rw
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - bridge
